[hugoVersion]
extended = true
min = "0.108.0"

[[imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/components/preloader"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/components/social-share"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/components/cookie-consent"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/components/render-link"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/icons/font-awesome"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/images"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/collapse"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/video"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/tabs"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/image"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/gallery"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/youtube-lite"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/vimeo-lite"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/seo-tools/google-tag-manager"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/seo-tools/site-verifications"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/seo-tools/basic-seo"

[[imports]]
path = "github.com/gethugothemes/hugo-modules/gzip-caching"
