---
name: SEO CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.9.2
        with:
          fail: true
          args: --timeout 60 --max-redirects 10 -a 403,500,502,503,504 .

  seo_spy_orphan_pages:
    runs-on: ubuntu-latest
    name: Check orphan pages
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1
        with:
          submodules: true

      - name: Checkout SEO Spy
        uses: actions/checkout@v4.1.1
        with:
          repository: 3mdeb/seo-spy
          path: seo-spy

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r seo-spy/requirements.txt

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          extended: true

      - name: Serve site
        run: |
          npm install postcss-cli
          hugo
          hugo serve -b http://localhost:1313 --bind=0.0.0.0 &

      - name: Check orphan pages
        uses: 3mdeb/seo-spy-action@main
        with:
          domain: "http://localhost:1313"

  seo_spy_canonical_links:
    runs-on: ubuntu-latest
    name: Check canonical links
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1
        with:
          submodules: true

      - name: Checkout SEO Spy
        uses: actions/checkout@v4.1.1
        with:
          repository: 3mdeb/seo-spy
          path: seo-spy

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r seo-spy/requirements.txt

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          extended: true

      - name: Serve site
        run: |
          npm install postcss-cli
          hugo
          hugo serve -b http://localhost:1313 --bind=0.0.0.0 &

      - name: Check canonical links
        uses: 3mdeb/seo-spy-action@main
        with:
          domain: 'http://localhost:1313'
          args: '-c'
